<<<<<<< HEAD
services:
  app:
    build: .
    ports: ["3000:3000"]
    depends_on: [db, prometheus]
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: taskflow
  prometheus:
    image: prom/prometheus
    ports: ["9090:9090"]
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    ports: ["3001:3000"]
=======
services:
  app:
    build: .
    ports: ["3000:3000"]
    depends_on: [db, prometheus]
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: taskflow
  prometheus:
    image: prom/prometheus
    ports: ["9090:9090"]
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    ports: ["3001:3000"]
>>>>>>> d70ebf2dc433eb0293c604a2c53a9f3bed25aca9
